# Generated by Django 3.2.12 on 2022-03-29 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='project')),
                ('color', models.CharField(choices=[('slategray', 'gray'), ('crimson', 'red'), ('blue', 'blue'), ('mediumaquamarine', 'skyblue'), ('darkslategray', 'deepgreen'), ('naby', 'naby'), ('forestgreen', 'green')], max_length=100, verbose_name='color')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100, verbose_name='タスク')),
                ('status', models.IntegerField(choices=[(0, '待機'), (1, '取組中'), (2, '完了')], verbose_name='状況')),
                ('createdDate', models.DateTimeField(blank=True, null=True, verbose_name='開始日')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='締め切り')),
                ('finishedDate', models.DateTimeField(blank=True, null=True, verbose_name='達成した日')),
                ('priority', models.CharField(choices=[('high', 'high'), ('midle', 'midle'), ('low', 'low')], max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='gantapp.projects')),
            ],
        ),
    ]
