# Generated by Django 3.2.12 on 2022-02-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='タスク')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100, verbose_name='タスク')),
                ('status', models.IntegerField(choices=[(0, '待機'), (1, '取組中'), (2, '完了')], verbose_name='状況')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='開始日')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='締め切り')),
                ('finishedDate', models.DateTimeField(blank=True, null=True, verbose_name='達成した日')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='gantapp.projects')),
            ],
        ),
    ]
