# Generated by Django 3.2.12 on 2022-02-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='createdDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
