# Generated by Django 3.2.12 on 2022-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantapp', '0003_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='color',
            field=models.CharField(default='red', max_length=100, verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('midle', 'midle'), ('low', 'low')], max_length=50),
        ),
    ]
