# Generated by Django 3.2.12 on 2022-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantapp', '0004_auto_20220320_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='color',
            field=models.CharField(default='red', max_length=100, verbose_name='color'),
        ),
    ]
